package main

import (
	"crypto/tls"
	"fmt"
	"io"
	"net"
	"net/http"
	"time"
	"regexp"
	"os"
	"bufio"
	"sync"
	"flag"
	"net/url"
	"strings"
)

var httpClient = &http.Client{
	CheckRedirect: func(req *http.Request, via []*http.Request) error {
		return http.ErrUseLastResponse
	},
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		DialContext: (&net.Dialer{
			Timeout:   30 * time.Second,
			KeepAlive: time.Second,
			DualStack: true,
		}).DialContext,
	},
}

func request(fullurl string, statusCode bool) string {
	req, err := http.NewRequest("GET", fullurl, nil)
	if err != nil {
		fmt.Println(err)
		return ""
	}

	req.Header.Add("User-Agent", "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36")

	resp, err := httpClient.Do(req)
	if err != nil {
		fmt.Println(err)
		return ""
	}
	defer resp.Body.Close()
	 if statusCode && resp.StatusCode != 404 {
	 	fmt.Printf("[Linkfinder] %s : %d\n", fullurl,  resp.StatusCode)
	 }

	var bodyString string
	if resp.StatusCode == http.StatusOK {
		bodyBytes, err := io.ReadAll(resp.Body)
		if err != nil {
			fmt.Println(err)
			return ""
		}
		bodyString = string(bodyBytes)
	}
	return bodyString
}

func regexGrep(content string, Burl string) {
	regex_map := map[string]string{
		"access_key_secret" : `access[_-]?key[_-]?secret(=| =|:| :)`,
		"access_secret" : `access[_-]?secret(=| =|:| :)`,
		"access_token" : `access[_-]?token(=| =|:| :)`,
		"account_sid" : `account[_-]?sid(=| =|:| :)`,
		"admin_email" : `admin[_-]?email(=| =|:| :)`,
		"admin_password" : `(admin).+(secret|token|key).+`,
		"adzerk_api_key" : `adzerk[_-]?api[_-]?key(=| =|:| :)`,
		"algolia_admin_key_1" : `algolia[_-]?admin[_-]?key[_-]?1(=| =|:| :)`,
		"algolia_admin_key_2" : `algolia[_-]?admin[_-]?key[_-]?2(=| =|:| :)`,
		"algolia_admin_key_mcm" : `algolia[_-]?admin[_-]?key[_-]?mcm(=| =|:| :)`,
		"algolia_api_key" : `algolia[_-]?api[_-]?key(=| =|:| :)`,
		"algolia_api_key_mcm" : `algolia[_-]?api[_-]?key[_-]?mcm(=| =|:| :)`,
		"algolia_api_key_search" : `algolia[_-]?api[_-]?key[_-]?search(=| =|:| :)`,
		"algolia_search_api_key" : `algolia[_-]?search[_-]?api[_-]?key(=| =|:| :)`,
		"algolia_search_key_1" : `algolia[_-]?search[_-]?key[_-]?1(=| =|:| :)`,
		"algolia_search_key" : `algolia[_-]?search[_-]?key(=| =|:| :)`,
		"alias_pass" : `alias[_-]?pass(=| =|:| :)`,
		"alicloud_access_key" : `alicloud[_-]?access[_-]?key(=| =|:| :)`,
		"alicloud_secret_key" : `alicloud[_-]?secret[_-]?key(=| =|:| :)`,
		"amazon_bucket_name" : `amazon[_-]?bucket[_-]?name(=| =|:| :)`,
		"amazon_mws_auth_token" : `amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`,
		"amazon_secret_access_key" : `amazon[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"amazon_sns_topic_disclosure" : `arn:aws:sns:[a-z0-9\-]+:[0-9]+:[A-Za-z0-9\-_]+`,
		"anaconda_token" : `anaconda[_-]?token(=| =|:| :)`,
		"android_docs_deploy_token" : `android[_-]?docs[_-]?deploy[_-]?token(=| =|:| :)`,
		"ansible_vault_password" : `ansible[_-]?vault[_-]?password(=| =|:| :)`,
		"aos_key" : `aos[_-]?key(=| =|:| :)`,
		"aos_sec" : `aos[_-]?sec(=| =|:| :)`,
		"apiary_api_key" : `apiary[_-]?api[_-]?key(=| =|:| :)`,
		"apigw_access_token" : `apigw[_-]?access[_-]?token(=| =|:| :)`,
		"api_key" : `api[_-]?key(=| =|:| :)`,
		"apikey_patterns" : `(?i)apikey[:](?:['"]?[a-zA-Z0-9-_|]+['"]?)`,
		"api_key_secret" : `api[_-]?key[_-]?secret(=| =|:| :)`,
		"api_key_sid" : `api[_-]?key[_-]?sid(=| =|:| :)`,
		"api_secret" : `api[_-]?secret(=| =|:| :)`,
		"app_bucket_perm" : `app[_-]?bucket[_-]?perm(=| =|:| :)`,
		"appclientsecret" : `appclientsecret(=| =|:| :)`,
		"apple_id_password" : `apple[_-]?id[_-]?password(=| =|:| :)`,
		"app_report_token_key" : `app[_-]?report[_-]?token[_-]?key(=| =|:| :)`,
		"app_secrete" : `app[_-]?secrete(=| =|:| :)`,
		"app_token" : `app[_-]?token(=| =|:| :)`,
		"argos_token" : `argos[_-]?token(=| =|:| :)`,
		"artifactory_api_token_disclosure" : `(?:\s|=|:|"|^)AKC[a-zA-Z0-9]{10,}`,
		"artifactory" : `(artifactory.{0,50}("|')?[a-zA-Z0-9=]{112}("|')?)`,
		"artifactory_key" : `artifactory[_-]?key(=| =|:| :)`,
		"artifactory_password_disclosure" : `(?:\s|=|:|"|^)AP[\dABCDEF][a-zA-Z0-9]{8,}`,
		"artifacts_aws_access_key_id" : `artifacts[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"artifacts_aws_secret_access_key" : `artifacts[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"artifacts_bucket" : `artifacts[_-]?bucket(=| =|:| :)`,
		"artifacts_key" : `artifacts[_-]?key(=| =|:| :)`,
		"artifacts_secret" : `artifacts[_-]?secret(=| =|:| :)`,
		"assistant_iam_apikey" : `assistant[_-]?iam[_-]?apikey(=| =|:| :)`,
		"auth0_api_clientsecret" : `auth0[_-]?api[_-]?clientsecret(=| =|:| :)`,
		"auth0_client_secret" : `auth0[_-]?client[_-]?secret(=| =|:| :)`,
		"author_email_addr" : `author[_-]?email[_-]?addr(=| =|:| :)`,
		"author_npm_api_key" : `author[_-]?npm[_-]?api[_-]?key(=| =|:| :)`,
		"auth_token" : `auth[_-]?token(=| =|:| :)`,
		"aws_access" : `aws[_-]?access(=| =|:| :)`,
		"aws_access_key" : `aws[_-]?access[_-]?key(=| =|:| :)`,
		"aws_access_key_id" : `(?:A3T|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[a-zA-Z0-9-_]{12,}`,
		"awsaccesskeyid" : `awsaccesskeyid(=| =|:| :)`,
		"aws_access_key_id_value" : `(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}`,
		"aws_api_gateway" : `[0-9a-z]+.execute-api.[0-9a-z.-_]+.amazonaws.com`,
		"aws_api_key" : `AKIA[0-9A-Z]{16}`,
		"aws_appsync_graphql_key" : `da2-[a-z0-9]{26}`,
		"aws_arn" : `arn:aws:[a-z0-9-]+:[a-z]{2}-[a-z]+-[0-9]+:[0-9]+:.+`,
		"aws_client_id" : `(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}`,
		"aws_cloudfront" : `[0-9a-z.-_]+.cloudfront.net`,
		"awscn_access_key_id" : `awscn[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"awscn_secret_access_key" : `awscn[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"aws_cognito_pool_id" : `:[0-9A-Za-z]{8}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{4}-[0-9A-Za-z]{12}`,
		"aws_config_accesskeyid" : `aws[_-]?config[_-]?accesskeyid(=| =|:| :)`,
		"aws_config_secretaccesskey" : `aws[_-]?config[_-]?secretaccesskey(=| =|:| :)`,
		"aws_ec2_external" : `ec2-[0-9a-z.-_]+.compute(-1)?.amazonaws.com`,
		"aws_ec2_internal" : `[0-9a-z.-_]+.compute(-1)?.internal`,
		"aws_elasticcache" : `[0-9a-z.-_]+.cache.amazonaws.com`,
		"aws_elb" : `[0-9a-z.-_]+.elb.amazonaws.com`,
		"aws_key" : `aws[_-]?key(=| =|:| :)`,
		"aws_mws_id" : `mzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`,
		"aws_mws_key" : `amzn.mws.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`,
		"aws_patterns" : `(?i)(?:accesskeyid|secretaccesskey|aws_access_key_id|aws_secret_access_key)`,
		"aws_rds" : `[0-9a-z.-_]+.rds.amazonaws.com`,
		"aws_s3" : `([a-zA-Z0-9_-]+.s3.[a-z0-9_-]+.amazonaws.com)`,
		"aws_s3_bucket" : `s3://[0-9a-z.-_/]+`,
		"aws_s3_endpoint" : `[a-zA-Z0-9.-_]+.s3.[a-zA-Z0-9.-_]+.amazonaws.com`,
		"aws_secret_access_key" : `aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"aws_secret" : `aws[_-]?secret(=| =|:| :)`,
		"awssecretkey" : `awssecretkey(=| =|:| :)`,
		"aws_secret_key" : `(?i)aws(.{0,20})?(?-i)['"][0-9a-zA-Z/+]{40}['"]`,
		"aws_secrets" : `aws[_-]?secrets(=| =|:| :)`,
		"aws_ses_access_key_id" : `aws[_-]?ses[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"aws_ses_secret_access_key" : `aws[_-]?ses[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"b2_app_key" : `b2[_-]?app[_-]?key(=| =|:| :)`,
		"b2_bucket" : `b2[_-]?bucket(=| =|:| :)`,
		"basic_auth_credentials" : `([a-zA-Z0-9]+:[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+)`,
		"basic_token" : `basic [a-zA-Z0-9_\-:\.=]+`,
		"bearer_token" : `(bearer).+`,
		"bintray_api_key" : `bintray[_-]?api[_-]?key(=| =|:| :)`,
		"bintray_apikey" : `bintray[_-]?apikey(=| =|:| :)`,
		"bintray_gpg_password" : `bintray[_-]?gpg[_-]?password(=| =|:| :)`,
		"bintray_key" : `bintray[_-]?key(=| =|:| :)`,
		"bintraykey" : `bintraykey(=| =|:| :)`,
		"bintray_token" : `bintray[_-]?token(=| =|:| :)`,
		"bitly_secret_key_disclosure" : `R_[0-9a-f]{32}`,
		"bluemix_api_key" : `bluemix[_-]?api[_-]?key(=| =|:| :)`,
		"bluemix_auth" : `bluemix[_-]?auth(=| =|:| :)`,
		"bluemix_pass" : `bluemix[_-]?pass(=| =|:| :)`,
		"bluemix_pass_prod" : `bluemix[_-]?pass[_-]?prod(=| =|:| :)`,
		"bluemix_password" : `bluemix[_-]?password(=| =|:| :)`,
		"bluemix_pwd" : `bluemix[_-]?pwd(=| =|:| :)`,
		"bluemix_username" : `bluemix[_-]?username(=| =|:| :)`,
		"brackets_repo_oauth_token" : `brackets[_-]?repo[_-]?oauth[_-]?token(=| =|:| :)`,
		"braintree_api_key" : `access_token$production$[0-9a-z]{16}$[0-9a-f]{32}`,
		"browser_stack_access_key" : `browser[_-]?stack[_-]?access[_-]?key(=| =|:| :)`,
		"browserstack_access_key" : `browserstack[_-]?access[_-]?key(=| =|:| :)`,
		"bucketeer_aws_access_key_id" : `bucketeer[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"bucketeer_aws_secret_access_key" : `bucketeer[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"built_branch_deploy_key" : `built[_-]?branch[_-]?deploy[_-]?key(=| =|:| :)`,
		"bundlesize_github_token" : `bundlesize[_-]?github[_-]?token(=| =|:| :)`,
		"bx_password" : `bx[_-]?password(=| =|:| :)`,
		"bx_username" : `bx[_-]?username(=| =|:| :)`,
		"cache_s3_secret_key" : `cache[_-]?s3[_-]?secret[_-]?key(=| =|:| :)`,
		"cargo_token" : `cargo[_-]?token(=| =|:| :)`,
		"cattle_access_key" : `cattle[_-]?access[_-]?key(=| =|:| :)`,
		"cattle_agent_instance_auth" : `cattle[_-]?agent[_-]?instance[_-]?auth(=| =|:| :)`,
		"cattle_secret_key" : `cattle[_-]?secret[_-]?key(=| =|:| :)`,
		"censys_secret" : `censys[_-]?secret(=| =|:| :)`,
		"certificate_password" : `certificate[_-]?password(=| =|:| :)`,
		"cf_password" : `cf[_-]?password(=| =|:| :)`,
		"cheverny_token" : `cheverny[_-]?token(=| =|:| :)`,
		"chrome_client_secret" : `chrome[_-]?client[_-]?secret(=| =|:| :)`,
		"chrome_refresh_token" : `chrome[_-]?refresh[_-]?token(=| =|:| :)`,
		"ci_deploy_password" : `ci[_-]?deploy[_-]?password(=| =|:| :)`,
		"ci_project_url" : `ci[_-]?project[_-]?url(=| =|:| :)`,
		"ci_registry_user" : `ci[_-]?registry[_-]?user(=| =|:| :)`,
		"ci_server_name" : `ci[_-]?server[_-]?name(=| =|:| :)`,
		"ci_user_token" : `ci[_-]?user[_-]?token(=| =|:| :)`,
		"claimr_database" : `claimr[_-]?database(=| =|:| :)`,
		"claimr_db" : `claimr[_-]?db(=| =|:| :)`,
		"claimr_superuser" : `claimr[_-]?superuser(=| =|:| :)`,
		"claimr_token" : `claimr[_-]?token(=| =|:| :)`,
		"cli_e2e_cma_token" : `cli[_-]?e2e[_-]?cma[_-]?token(=| =|:| :)`,
		"client_secret" : `client[_-]?secret(=| =|:| :)`,
		"clojars_password" : `clojars[_-]?password(=| =|:| :)`,
		"cloudant_archived_database" : `cloudant[_-]?archived[_-]?database(=| =|:| :)`,
		"cloudant_audited_database" : `cloudant[_-]?audited[_-]?database(=| =|:| :)`,
		"cloudant_database" : `cloudant[_-]?database(=| =|:| :)`,
		"cloudant_instance" : `cloudant[_-]?instance(=| =|:| :)`,
		"cloudant_order_database" : `cloudant[_-]?order[_-]?database(=| =|:| :)`,
		"cloudant_parsed_database" : `cloudant[_-]?parsed[_-]?database(=| =|:| :)`,
		"cloudant_password" : `cloudant[_-]?password(=| =|:| :)`,
		"cloudant_processed_database" : `cloudant[_-]?processed[_-]?database(=| =|:| :)`,
		"cloudant_service_database" : `cloudant[_-]?service[_-]?database(=| =|:| :)`,
		"cloud_api_key" : `cloud[_-]?api[_-]?key(=| =|:| :)`,
		"cloudflare_api_key" : `cloudflare[_-]?api[_-]?key(=| =|:| :)`,
		"cloudflare_auth_email" : `cloudflare[_-]?auth[_-]?email(=| =|:| :)`,
		"cloudflare_auth_key" : `cloudflare[_-]?auth[_-]?key(=| =|:| :)`,
		"cloudflare_email" : `cloudflare[_-]?email(=| =|:| :)`,
		"cloudinary_credentials_disclosure" : `cloudinary://[0-9]{15}:[0-9A-Za-z\-_]+@[0-9A-Za-z\-_]+`,
		"cloudinary_url" : `cloudinary[_-]?url(=| =|:| :)`,
		"cloudinary_url_staging" : `cloudinary[_-]?url[_-]?staging(=| =|:| :)`,
		"clu_repo_url" : `clu[_-]?repo[_-]?url(=| =|:| :)`,
		"clu_ssh_private_key_base64" : `clu[_-]?ssh[_-]?private[_-]?key[_-]?base64(=| =|:| :)`,
		"cn_access_key_id" : `cn[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"cn_secret_access_key" : `cn[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"cocoapods_trunk_email" : `cocoapods[_-]?trunk[_-]?email(=| =|:| :)`,
		"cocoapods_trunk_token" : `cocoapods[_-]?trunk[_-]?token(=| =|:| :)`,
		"codacy_project_token" : `codacy[_-]?project[_-]?token(=| =|:| :)`,
		"codeclimate" : `(codeclima.{0,50}("|')?[0-9a-f]{64}("|')?)`,
		"codeclimate_repo_token" : `codeclimate[_-]?repo[_-]?token(=| =|:| :)`,
		"codecov_token" : `codecov[_-]?token(=| =|:| :)`,
		"coding_token" : `coding[_-]?token(=| =|:| :)`,
		"conekta_apikey" : `conekta[_-]?apikey(=| =|:| :)`,
		"consumer_key" : `consumer[_-]?key(=| =|:| :)`,
		"consumerkey" : `consumerkey(=| =|:| :)`,
		"contentful_access_token" : `contentful[_-]?access[_-]?token(=| =|:| :)`,
		"contentful_cma_test_token" : `contentful[_-]?cma[_-]?test[_-]?token(=| =|:| :)`,
		"contentful_integration_management_token" : `contentful[_-]?integration[_-]?management[_-]?token(=| =|:| :)`,
		"contentful_management_api_access_token" : `contentful[_-]?management[_-]?api[_-]?access[_-]?token(=| =|:| :)`,
		"contentful_management_api_access_token_new" : `contentful[_-]?management[_-]?api[_-]?access[_-]?token[_-]?new(=| =|:| :)`,
		"contentful_php_management_test_token" : `contentful[_-]?php[_-]?management[_-]?test[_-]?token(=| =|:| :)`,
		"contentful_test_org_cma_token" : `contentful[_-]?test[_-]?org[_-]?cma[_-]?token(=| =|:| :)`,
		"contentful_v2_access_token" : `contentful[_-]?v2[_-]?access[_-]?token(=| =|:| :)`,
		"conversation_password" : `conversation[_-]?password(=| =|:| :)`,
		"conversation_username" : `conversation[_-]?username(=| =|:| :)`,
		"cos_secrets" : `cos[_-]?secrets(=| =|:| :)`,
		"coveralls_api_token" : `coveralls[_-]?api[_-]?token(=| =|:| :)`,
		"coveralls_repo_token" : `coveralls[_-]?repo[_-]?token(=| =|:| :)`,
		"coveralls_token" : `coveralls[_-]?token(=| =|:| :)`,
		"coverity_scan_token" : `coverity[_-]?scan[_-]?token(=| =|:| :)`,
		"cypress_record_key" : `cypress[_-]?record[_-]?key(=| =|:| :)`,
		"danger_github_api_token" : `danger[_-]?github[_-]?api[_-]?token(=| =|:| :)`,
		"database_host" : `database[_-]?host(=| =|:| :)`,
		"database_name" : `database[_-]?name(=| =|:| :)`,
		"database_password" : `database[_-]?password(=| =|:| :)`,
		"database_port" : `database[_-]?port(=| =|:| :)`,
		"database_user" : `database[_-]?user(=| =|:| :)`,
		"database_username" : `database[_-]?username(=| =|:| :)`,
		"datadog_api_key" : `datadog[_-]?api[_-]?key(=| =|:| :)`,
		"datadog_app_key" : `datadog[_-]?app[_-]?key(=| =|:| :)`,
		"db_connection" : `db[_-]?connection(=| =|:| :)`,
		"db_database" : `db[_-]?database(=| =|:| :)`,
		"db_host" : `db[_-]?host(=| =|:| :)`,
		"db_password" : `db[_-]?password(=| =|:| :)`,
		"db_pw" : `db[_-]?pw(=| =|:| :)`,
		"db_user" : `db[_-]?user(=| =|:| :)`,
		"db_username" : `db[_-]?username(=| =|:| :)`,
		"ddgc_github_token" : `ddgc[_-]?github[_-]?token(=| =|:| :)`,
		"ddg_test_email" : `ddg[_-]?test[_-]?email(=| =|:| :)`,
		"ddg_test_email_pw" : `ddg[_-]?test[_-]?email[_-]?pw(=| =|:| :)`,
		"deploy_password" : `deploy[_-]?password(=| =|:| :)`,
		"deploy_secure" : `deploy[_-]?secure(=| =|:| :)`,
		"deploy_token" : `deploy[_-]?token(=| =|:| :)`,
		"deploy_user" : `deploy[_-]?user(=| =|:| :)`,
		"dgpg_passphrase" : `dgpg[_-]?passphrase(=| =|:| :)`,
		"digitalocean_access_token" : `digitalocean[_-]?access[_-]?token(=| =|:| :)`,
		"digitalocean_space" : `(http(?:s)://[^><.'" 
		)]+.digitaloceanspaces.com)`,
		"digitalocean_ssh_key_body" : `digitalocean[_-]?ssh[_-]?key[_-]?body(=| =|:| :)`,
		"digitalocean_ssh_key_ids" : `digitalocean[_-]?ssh[_-]?key[_-]?ids(=| =|:| :)`,
		"discord_webhook_disclosure" : `https://discordapp\.com/api/webhooks/[0-9]+/[A-Za-z0-9\-]+`,
		"docker_hub_password" : `docker[_-]?hub[_-]?password(=| =|:| :)`,
		"dockerhub_password" : `dockerhub[_-]?password(=| =|:| :)`,
		"dockerhubpassword" : `dockerhubpassword(=| =|:| :)`,
		"docker_key" : `docker[_-]?key(=| =|:| :)`,
		"docker_pass" : `docker[_-]?pass(=| =|:| :)`,
		"docker_passwd" : `docker[_-]?passwd(=| =|:| :)`,
		"docker_password" : `docker[_-]?password(=| =|:| :)`,
		"docker_postgres_url" : `docker[_-]?postgres[_-]?url(=| =|:| :)`,
		"docker_token" : `docker[_-]?token(=| =|:| :)`,
		"doordash_auth_token" : `doordash[_-]?auth[_-]?token(=| =|:| :)`,
		"dropbox_oauth_bearer" : `dropbox[_-]?oauth[_-]?bearer(=| =|:| :)`,
		"droplet_travis_password" : `droplet[_-]?travis[_-]?password(=| =|:| :)`,
		"dsonar_login" : `dsonar[_-]?login(=| =|:| :)`,
		"dsonar_projectkey" : `dsonar[_-]?projectkey(=| =|:| :)`,
		"dynatrace_token" : `dt0[a-zA-Z]{1}[0-9]{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64}`,
		"elastic_cloud_auth" : `elastic[_-]?cloud[_-]?auth(=| =|:| :)`,
		"elasticsearch_password" : `elasticsearch[_-]?password(=| =|:| :)`,
		"encryption_password" : `encryption[_-]?password(=| =|:| :)`,
		"end_user_password" : `end[_-]?user[_-]?password(=| =|:| :)`,
		"env_github_oauth_token" : `env[_-]?github[_-]?oauth[_-]?token(=| =|:| :)`,
		"env_heroku_api_key" : `env[_-]?heroku[_-]?api[_-]?key(=| =|:| :)`,
		"env_key" : `env[_-]?key(=| =|:| :)`,
		"env_secret_access_key" : `env[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"env_secret" : `env[_-]?secret(=| =|:| :)`,
		"env_sonatype_password" : `env[_-]?sonatype[_-]?password(=| =|:| :)`,
		"eureka_awssecretkey" : `eureka[_-]?awssecretkey(=| =|:| :)`,
		"exp_password" : `exp[_-]?password(=| =|:| :)`,
		"facebook_access_token" : `EAACEdEose0cBA[0-9A-Za-z]+`,
		"facebook_client_id" : `(?i)(facebook|fb)(.{0,20})?['"][0-9]{13,17}`,
		"facebook_oauth" : `[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*['|"][0-9a-f]{32}['|"]`,
		"facebook_secret_key" : `(?i)(facebook|fb)(.{0,20})?(?-i)['"][0-9a-f]{32}`,
		"fcm_server_key" : `(?i)(AAAA[a-zA-Z0-9_-]{7}:[a-zA-Z0-9_-]{140})`,
		"file_password" : `file[_-]?password(=| =|:| :)`,
		"firebase_api_json" : `firebase[_-]?api[_-]?json(=| =|:| :)`,
		"firebase_api_token" : `firebase[_-]?api[_-]?token(=| =|:| :)`,
		"firebase_database_detect" : `[a-z0-9.-]+\.firebaseapp\.com`,
		"firebase_key" : `firebase[_-]?key(=| =|:| :)`,
		"firebase_project_develop" : `firebase[_-]?project[_-]?develop(=| =|:| :)`,
		"firebase_token" : `firebase[_-]?token(=| =|:| :)`,
		"firefox_secret" : `firefox[_-]?secret(=| =|:| :)`,
		"flask_secret_key" : `flask[_-]?secret[_-]?key(=| =|:| :)`,
		"flickr_api_key" : `flickr[_-]?api[_-]?key(=| =|:| :)`,
		"flickr_api_secret" : `flickr[_-]?api[_-]?secret(=| =|:| :)`,
		"fossa_api_key" : `fossa[_-]?api[_-]?key(=| =|:| :)`,
		"ftp_host" : `ftp[_-]?host(=| =|:| :)`,
		"ftp_login" : `ftp[_-]?login(=| =|:| :)`,
		"ftp_password" : `ftp[_-]?password(=| =|:| :)`,
		"ftp_pw" : `ftp[_-]?pw(=| =|:| :)`,
		"ftp_user" : `ftp[_-]?user(=| =|:| :)`,
		"ftp_username" : `ftp[_-]?username(=| =|:| :)`,
		"gcloud_bucket" : `gcloud[_-]?bucket(=| =|:| :)`,
		"gcloud_project" : `gcloud[_-]?project(=| =|:| :)`,
		"gcloud_service_key" : `gcloud[_-]?service[_-]?key(=| =|:| :)`,
		"gcp_api_key" : `(AIza[0-9A-Za-z-_]{35})`,
		"gcr_password" : `gcr[_-]?password(=| =|:| :)`,
		"gcs_bucket" : `gcs[_-]?bucket(=| =|:| :)`,
		"generic_api_key" : `[aA][pP][iI]_?[kK][eE][yY].*['|"][0-9a-zA-Z]{32,45}['|"]`,
		"generic_credit_card" : `^(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\d{3})\d{11})`,
		"generic_secret" : `[sS][eE][cC][rR][eE][tT].*[''|"][0-9a-zA-Z]{32,45}[''|"]`,
		"generic_webhook_secret" : `(webhook).+(secret|token|key).+`,
		"gh_api_key" : `gh[_-]?api[_-]?key(=| =|:| :)`,
		"ghb_token" : `ghb[_-]?token(=| =|:| :)`,
		"gh_email" : `gh[_-]?email(=| =|:| :)`,
		"gh_next_oauth_client_secret" : `gh[_-]?next[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)`,
		"gh_next_unstable_oauth_client_id" : `gh[_-]?next[_-]?unstable[_-]?oauth[_-]?client[_-]?id(=| =|:| :)`,
		"gh_next_unstable_oauth_client_secret" : `gh[_-]?next[_-]?unstable[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)`,
		"gh_oauth_client_secret" : `gh[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)`,
		"gh_oauth_token" : `gh[_-]?oauth[_-]?token(=| =|:| :)`,
		"ghost_api_key" : `ghost[_-]?api[_-]?key(=| =|:| :)`,
		"gh_repo_token" : `gh[_-]?repo[_-]?token(=| =|:| :)`,
		"gh_token" : `gh[_-]?token(=| =|:| :)`,
		"gh_unstable_oauth_client_secret" : `gh[_-]?unstable[_-]?oauth[_-]?client[_-]?secret(=| =|:| :)`,
		"git_author_email" : `git[_-]?author[_-]?email(=| =|:| :)`,
		"git_author_name" : `git[_-]?author[_-]?name(=| =|:| :)`,
		"git_committer_email" : `git[_-]?committer[_-]?email(=| =|:| :)`,
		"git_committer_name" : `git[_-]?committer[_-]?name(=| =|:| :)`,
		"git_email" : `git[_-]?email(=| =|:| :)`,
		"github_access_token" : `[a-zA-Z0-9_-]*:[a-zA-Z0-9_-]+@github.com*`,
		"github_api_key" : `github[_-]?api[_-]?key(=| =|:| :)`,
		"github_api_token" : `github[_-]?api[_-]?token(=| =|:| :)`,
		"github_auth" : `github[_-]?auth(=| =|:| :)`,
		"github_auth_token" : `github[_-]?auth[_-]?token(=| =|:| :)`,
		"github_client_secret" : `github[_-]?client[_-]?secret(=| =|:| :)`,
		"github_deploy_hb_doc_pass" : `github[_-]?deploy[_-]?hb[_-]?doc[_-]?pass(=| =|:| :)`,
		"github_deployment_token" : `github[_-]?deployment[_-]?token(=| =|:| :)`,
		"github" : `[gG][iI][tT][hH][uU][bB].*['|"][0-9a-zA-Z]{35,40}['|"]`,
		"github_hunter_token" : `github[_-]?hunter[_-]?token(=| =|:| :)`,
		"github_hunter_username" : `github[_-]?hunter[_-]?username(=| =|:| :)`,
		"github_key" : `github[_-]?key(=| =|:| :)`,
		"github_oauth" : `github[_-]?oauth(=| =|:| :)`,
		"github_oauth_token" : `github[_-]?oauth[_-]?token(=| =|:| :)`,
		"github_password" : `github[_-]?password(=| =|:| :)`,
		"github_pwd" : `github[_-]?pwd(=| =|:| :)`,
		"github_release_token" : `github[_-]?release[_-]?token(=| =|:| :)`,
		"github_repo" : `github[_-]?repo(=| =|:| :)`,
		"github_token" : `github[_-]?token(=| =|:| :)`,
		"github_tokens" : `github[_-]?tokens(=| =|:| :)`,
		"gitlab_user_email" : `gitlab[_-]?user[_-]?email(=| =|:| :)`,
		"git_name" : `git[_-]?name(=| =|:| :)`,
		"git_token" : `git[_-]?token(=| =|:| :)`,
		"gogs_password" : `gogs[_-]?password(=| =|:| :)`,
		"google_account_type" : `google[_-]?account[_-]?type(=| =|:| :)`,
		"google_api_key" : `AIza[0-9A-Za-z\-_]{35}`,
		"google_calendar_uri" : `https://www\.google\.com/calendar/embed\?src=[A-Za-z0-9%@&;=\-_\./]+`,
		"google_captcha" : `(6L[0-9A-Za-z-_]{38})`,
		"google_client_email" : `google[_-]?client[_-]?email(=| =|:| :)`,
		"google_client_id" : `google[_-]?client[_-]?id(=| =|:| :)`,
		"google_client_secret" : `google[_-]?client[_-]?secret(=| =|:| :)`,
		"google_cloud_platform_api_key" : `^(v[0-9]\.)?[0-9a-f]{40}$`,
		"google_cloud_platform_oauth" : `[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com`,
		"google_drive_api_key" : `AIza[0-9A-Za-z\-_]{35}`,
		"google_drive_oauth" : `[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com`,
		"google_(gcp)_service-account" : `"type": "service_account"`,
		"google_gmail_api_key" : `AIza[0-9A-Za-z\-_]{35}`,
		"google_gmail_oauth" : `[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com`,
		"google_maps_api_key" : `google[_-]?maps[_-]?api[_-]?key(=| =|:| :)`,
		"google_oauth_access_key" : `ya29\.[0-9A-Za-z\-_]+`,
		"google_oauth_access_token" : `ya29\.[0-9A-Za-z\-_]+`,
		"google_oauth_id" : `[0-9]+-[0-9a-z_]{32}.apps.googleusercontent.com`,
		"google_oauth" : `(ya29.[0-9A-Za-z-_]+)`,
		"google_patterns" : `(?i)(?:google_client_id|google_client_secret|google_client_token)`,
		"google_private_key" : `google[_-]?private[_-]?key(=| =|:| :)`,
		"google_url" : `([0-9]{12}-[a-z0-9]{32}.apps.googleusercontent.com)`,
		"google_youtube_api_key" : `AIza[0-9A-Za-z\-_]{35}`,
		"google_youtube_oauth" : `[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com`,
		"gpg_key_name" : `gpg[_-]?key[_-]?name(=| =|:| :)`,
		"gpg_keyname" : `gpg[_-]?keyname(=| =|:| :)`,
		"gpg_ownertrust" : `gpg[_-]?ownertrust(=| =|:| :)`,
		"gpg_passphrase" : `gpg[_-]?passphrase(=| =|:| :)`,
		"gpg_private_key" : `gpg[_-]?private[_-]?key(=| =|:| :)`,
		"gpg_secret_keys" : `gpg[_-]?secret[_-]?keys(=| =|:| :)`,
		"gradle_publish_key" : `gradle[_-]?publish[_-]?key(=| =|:| :)`,
		"gradle_publish_secret" : `gradle[_-]?publish[_-]?secret(=| =|:| :)`,
		"gradle_signing_key_id" : `gradle[_-]?signing[_-]?key[_-]?id(=| =|:| :)`,
		"gradle_signing_password" : `gradle[_-]?signing[_-]?password(=| =|:| :)`,
		"gren_github_token" : `gren[_-]?github[_-]?token(=| =|:| :)`,
		"grgit_user" : `grgit[_-]?user(=| =|:| :)`,
		"hab_auth_token" : `hab[_-]?auth[_-]?token(=| =|:| :)`,
		"hab_key" : `hab[_-]?key(=| =|:| :)`,
		"hb_codesign_gpg_pass" : `hb[_-]?codesign[_-]?gpg[_-]?pass(=| =|:| :)`,
		"hb_codesign_key_pass" : `hb[_-]?codesign[_-]?key[_-]?pass(=| =|:| :)`,
		"heroku_api_key_api_key" : `([h|H][e|E][r|R][o|O][k|K][u|U].{0,30}[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})`,
		"heroku_api_key" : `[hH][eE][rR][oO][kK][uU].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}`,
		"heroku_email" : `heroku[_-]?email(=| =|:| :)`,
		"heroku_token" : `heroku[_-]?token(=| =|:| :)`,
		"hockeyapp" : `hockey.{0,50}("|')?[0-9a-f]{32}("|')?`,
		"hockeyapp_token" : `hockeyapp[_-]?token(=| =|:| :)`,
		"homebrew_github_api_token" : `homebrew[_-]?github[_-]?api[_-]?token(=| =|:| :)`,
		"hub_dxia2_password" : `hub[_-]?dxia2[_-]?password(=| =|:| :)`,
		"ij_repo_password" : `ij[_-]?repo[_-]?password(=| =|:| :)`,
		"ij_repo_username" : `ij[_-]?repo[_-]?username(=| =|:| :)`,
		"index_name" : `index[_-]?name(=| =|:| :)`,
		"integration_test_api_key" : `integration[_-]?test[_-]?api[_-]?key(=| =|:| :)`,
		"integration_test_appid" : `integration[_-]?test[_-]?appid(=| =|:| :)`,
		"internal_secrets" : `internal[_-]?secrets(=| =|:| :)`,
		"ios_docs_deploy_token" : `ios[_-]?docs[_-]?deploy[_-]?token(=| =|:| :)`,
		"itest_gh_token" : `itest[_-]?gh[_-]?token(=| =|:| :)`,
		"jdbc_connection_string_disclosure" : `jdbc:[a-z:]+://[A-Za-z0-9\.\-_:;=/@?,&]+`,
		"jdbc_databaseurl" : `jdbc[_-]?databaseurl(=| =|:| :)`,
		"jdbc_host" : `jdbc[_-]?host(=| =|:| :)`,
		"jdbc" : `mysql: jdbc:mysql(=| =|:| :)`,
		"json_web1_token" : `(eyJ[a-zA-Z0-9-]{10,}.eyJ[a-zA-Z0-9-]{10,}.[a-zA-Z0-9-]{10,})`,
		"jwt_secret" : `jwt[_-]?secret(=| =|:| :)`,
		"jwt_token" : `eyJ[a-zA-Z0-9]{10,}\.eyJ[a-zA-Z0-9]{10,}\.[a-zA-Z0-9_\-]{10,}`,
		"kafka_admin_url" : `kafka[_-]?admin[_-]?url(=| =|:| :)`,
		"kafka_instance_name" : `kafka[_-]?instance[_-]?name(=| =|:| :)`,
		"kafka_rest_url" : `kafka[_-]?rest[_-]?url(=| =|:| :)`,
		"keystore_pass" : `keystore[_-]?pass(=| =|:| :)`,
		"kovan_private_key" : `kovan[_-]?private[_-]?key(=| =|:| :)`,
		"kubecfg_s3_path" : `kubecfg[_-]?s3[_-]?path(=| =|:| :)`,
		"kubeconfig" : `kubeconfig(=| =|:| :)`,
		"kxoltsn3vogdop92m" : `kxoltsn3vogdop92m(=| =|:| :)`,
		"leanplum_key" : `leanplum[_-]?key(=| =|:| :)`,
		"lektor_deploy_password" : `lektor[_-]?deploy[_-]?password(=| =|:| :)`,
		"lektor_deploy_username" : `lektor[_-]?deploy[_-]?username(=| =|:| :)`,
		"lighthouse_api_key" : `lighthouse[_-]?api[_-]?key(=| =|:| :)`,
		"linkedin_client_id" : `(linkedin(.{0,20})?(?-i)['"][0-9a-z]{12}['"])`,
		"linkedin_client_secretor_lottie_s3_api_key" : `linkedin[_-]?client[_-]?secretor lottie[_-]?s3[_-]?api[_-]?key(=| =|:| :)`,
		"linkedin_secret_key" : `(linkedin(.{0,20})?['"][0-9a-z]{16}['"])`,
		"linux_signing_key" : `linux[_-]?signing[_-]?key(=| =|:| :)`,
		"ll_publish_url" : `ll[_-]?publish[_-]?url(=| =|:| :)`,
		"ll_shared_key" : `ll[_-]?shared[_-]?key(=| =|:| :)`,
		"looker_test_runner_client_secret" : `looker[_-]?test[_-]?runner[_-]?client[_-]?secret(=| =|:| :)`,
		"lottie_happo_api_key" : `lottie[_-]?happo[_-]?api[_-]?key(=| =|:| :)`,
		"lottie_happo_secret_key" : `lottie[_-]?happo[_-]?secret[_-]?key(=| =|:| :)`,
		"lottie_s3_secret_key" : `lottie[_-]?s3[_-]?secret[_-]?key(=| =|:| :)`,
		"lottie_upload_cert_key_password" : `lottie[_-]?upload[_-]?cert[_-]?key[_-]?password(=| =|:| :)`,
		"lottie_upload_cert_key_store_password" : `lottie[_-]?upload[_-]?cert[_-]?key[_-]?store[_-]?password(=| =|:| :)`,
		"magento_auth_password" : `magento[_-]?auth[_-]?password(=| =|:| :)`,
		"magento_auth_username" : `magento[_-]?auth[_-]?username (=| =|:| :)`,
		"magento_password" : `magento[_-]?password(=| =|:| :)`,
		"mailchimp_api" : `[0-9a-f]{32}-us[0-9]{1,2}`,
		"mailchimp_api_key" : `[0-9a-f]{32}-us[0-9]{1,2}`,
		"mailchimp_key" : `mailchimp[_-]?key(=| =|:| :)`,
		"mailchimp" : `(W(?:[a-f0-9]{32}(-us[0-9]{1,2}))a-zA-Z0-9)`,
		"mailer_password" : `mailer[_-]?password(=| =|:| :)`,
		"mailgun_api_key" : `key-[0-9a-zA-Z]{32}`,
		"mailgun_apikey" : `mailgun[_-]?apikey(=| =|:| :)`,
		"mailgun" : `(key-[0-9a-f]{32})`,
		"mailgun_password" : `mailgun[_-]?password(=| =|:| :)`,
		"mailgun_priv_key" : `mailgun[_-]?priv[_-]?key(=| =|:| :)`,
		"mailgun_pub_apikey" : `mailgun[_-]?pub[_-]?apikey(=| =|:| :)`,
		"mailgun_pub_key" : `mailgun[_-]?pub[_-]?key(=| =|:| :)`,
		"mailgun_secret_api_key" : `mailgun[_-]?secret[_-]?api[_-]?key(=| =|:| :)`,
		"mail_password" : `mail[_-]?password(=| =|:| :)`,
		"manage_key" : `manage[_-]?key(=| =|:| :)`,
		"managementapiaccesstoken" : `managementapiaccesstoken(=| =|:| :)`,
		"management_token" : `management[_-]?token(=| =|:| :)`,
		"manage_secret" : `manage[_-]?secret(=| =|:| :)`,
		"mandrill_api_key" : `mandrill[_-]?api[_-]?key(=| =|:| :)`,
		"manifest_app_token" : `manifest[_-]?app[_-]?token(=| =|:| :)`,
		"manifest_app_url" : `manifest[_-]?app[_-]?url(=| =|:| :)`,
		"mapbox_access_token" : `mapbox[_-]?access[_-]?token(=| =|:| :)`,
		"mapboxaccesstoken" : `mapboxaccesstoken(=| =|:| :)`,
		"mapbox_api_token" : `mapbox[_-]?api[_-]?token(=| =|:| :)`,
		"mapbox_aws_access_key_id" : `mapbox[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"mapbox_aws_secret_access_key" : `mapbox[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"master_password" : `(master_password).+`,
		"mfa_token" : `(?:token=[A-Za-z0-9\s_]*[A-Za-z0-9][A-Za-z0-9\s_])`,
		"mg_api_key" : `mg[_-]?api[_-]?key(=| =|:| :)`,
		"mg_public_api_key" : `mg[_-]?public[_-]?api[_-]?key(=| =|:| :)`,
		"mh_apikey" : `mh[_-]?apikey(=| =|:| :)`,
		"mh_password" : `mh[_-]?password(=| =|:| :)`,
		"microsoft_teams_webhook" : `https://outlook\.office\.com/webhook/[A-Za-z0-9\-@]+/IncomingWebhook/[A-Za-z0-9\-]+/[A-Za-z0-9\-]+`,
		"mile_zero_key" : `mile[_-]?zero[_-]?key(=| =|:| :)`,
		"minio_access_key" : `minio[_-]?access[_-]?key(=| =|:| :)`,
		"minio_secret_key" : `minio[_-]?secret[_-]?key(=| =|:| :)`,
		"multi_bob_sid" : `multi[_-]?bob[_-]?sid(=| =|:| :)`,
		"multi_connect_sid" : `multi[_-]?connect[_-]?sid(=| =|:| :)`,
		"multi_disconnect_sid" : `multi[_-]?disconnect[_-]?sid(=| =|:| :)`,
		"multi_workflow_sid" : `multi[_-]?workflow[_-]?sid(=| =|:| :)`,
		"multi_workspace_sid" : `multi[_-]?workspace[_-]?sid(=| =|:| :)`,
		"my_secret_env" : `my[_-]?secret[_-]?env(=| =|:| :)`,
		"mysql_database" : `mysql[_-]?database(=| =|:| :)`,
		"mysql_hostname" : `mysql[_-]?hostname(=| =|:| :)`,
		"mysqlmasteruser" : `mysqlmasteruser(=| =|:| :)`,
		"mysql_password" : `mysql[_-]?password(=| =|:| :)`,
		"mysql_root_password" : `mysql[_-]?root[_-]?password(=| =|:| :)`,
		"mysqlsecret" : `mysqlsecret(=| =|:| :)`,
		"mysql_user" : `mysql[_-]?user(=| =|:| :)`,
		"mysql_username" : `mysql[_-]?username(=| =|:| :)`,
		"nativeevents" : `nativeevents(=| =|:| :)`,
		"netlify_api_key" : `netlify[_-]?api[_-]?key(=| =|:| :)`,
		"newrelic_admin_api_key" : `(?i)NRAA-[a-f0-9]{27}`,
		"new_relic_beta_token" : `new[_-]?relic[_-]?beta[_-]?token(=| =|:| :)`,
		"newrelic_insights_api_key" : `(?i)NRI(?:I|Q)-[A-Za-z0-9\-_]{32}`,
		"newrelic_rest_api_key" : `(?i)NRRA-[a-f0-9]{42}`,
		"newrelic_synthetics_location_key" : `(?i)NRSP-[a-z]{2}[0-9]{2}[a-f0-9]{31}`,
		"nexus_password" : `nexus[_-]?password(=| =|:| :)`,
		"nexuspassword" : `nexuspassword(=| =|:| :)`,
		"ngrok_auth_token" : `ngrok[_-]?auth[_-]?token(=| =|:| :)`,
		"ngrok_token" : `ngrok[_-]?token(=| =|:| :)`,
		"node_env" : `node[_-]?env(=| =|:| :)`,
		"node_pre_gyp_accesskeyid" : `node[_-]?pre[_-]?gyp[_-]?accesskeyid(=| =|:| :)`,
		"node_pre_gyp_github_token" : `node[_-]?pre[_-]?gyp[_-]?github[_-]?token(=| =|:| :)`,
		"node_pre_gyp_secretaccesskey" : `node[_-]?pre[_-]?gyp[_-]?secretaccesskey(=| =|:| :)`,
		"non_token" : `non[_-]?token(=| =|:| :)`,
		"now_token" : `now[_-]?token(=| =|:| :)`,
		"npm_api_key" : `npm[_-]?api[_-]?key(=| =|:| :)`,
		"npm_api_token" : `npm[_-]?api[_-]?token(=| =|:| :)`,
		"npm_auth_token" : `npm[_-]?auth[_-]?token(=| =|:| :)`,
		"npm_email" : `npm[_-]?email(=| =|:| :)`,
		"npm_password" : `npm[_-]?password(=| =|:| :)`,
		"npm_secret_key" : `npm[_-]?secret[_-]?key(=| =|:| :)`,
		"nuget_api_key" : `nuget[_-]?api[_-]?key(=| =|:| :)`,
		"nuget_apikey" : `nuget[_-]?apikey(=| =|:| :)`,
		"nuget_key" : `nuget[_-]?key(=| =|:| :)`,
		"numbers_service_pass" : `numbers[_-]?service[_-]?pass(=| =|:| :)`,
		"oauth_token" : `oauth[_-]?token(=| =|:| :)`,
		"object_storage_password" : `object[_-]?storage[_-]?password(=| =|:| :)`,
		"object_storage_region_name" : `object[_-]?storage[_-]?region[_-]?name(=| =|:| :)`,
		"object_store_bucket" : `object[_-]?store[_-]?bucket(=| =|:| :)`,
		"object_store_creds" : `object[_-]?store[_-]?creds(=| =|:| :)`,
		"oc_pass" : `oc[_-]?pass(=| =|:| :)`,
		"octest_app_password" : `octest[_-]?app[_-]?password(=| =|:| :)`,
		"octest_app_username" : `octest[_-]?app[_-]?username(=| =|:| :)`,
		"octest_password" : `octest[_-]?password(=| =|:| :)`,
		"ofta_key" : `ofta[_-]?key(=| =|:| :)`,
		"ofta_region" : `ofta[_-]?region(=| =|:| :)`,
		"ofta_secret" : `ofta[_-]?secret(=| =|:| :)`,
		"okta_client_token" : `okta[_-]?client[_-]?token(=| =|:| :)`,
		"okta_oauth2_client_secret" : `okta[_-]?oauth2[_-]?client[_-]?secret(=| =|:| :)`,
		"okta_oauth2_clientsecret" : `okta[_-]?oauth2[_-]?clientsecret(=| =|:| :)`,
		"omise_key" : `omise[_-]?key(=| =|:| :)`,
		"omise_pkey" : `omise[_-]?pkey(=| =|:| :)`,
		"omise_pubkey" : `omise[_-]?pubkey(=| =|:| :)`,
		"omise_skey" : `omise[_-]?skey(=| =|:| :)`,
		"onesignal_api_key" : `onesignal[_-]?api[_-]?key(=| =|:| :)`,
		"onesignal_user_auth_key" : `onesignal[_-]?user[_-]?auth[_-]?key(=| =|:| :)`,
		"open_whisk_key" : `open[_-]?whisk[_-]?key(=| =|:| :)`,
		"openwhisk_key" : `openwhisk[_-]?key(=| =|:| :)`,
		"org_gradle_project_sonatype_nexus_password" : `org[_-]?gradle[_-]?project[_-]?sonatype[_-]?nexus[_-]?password(=| =|:| :)`,
		"org_project_gradle_sonatype_nexus_password" : `org[_-]?project[_-]?gradle[_-]?sonatype[_-]?nexus[_-]?password(=| =|:| :)`,
		"os_auth_url" : `os[_-]?auth[_-]?url(=| =|:| :)`,
		"os_password" : `os[_-]?password(=| =|:| :)`,
		"ossrh_jira_password" : `ossrh[_-]?jira[_-]?password(=| =|:| :)`,
		"ossrh_pass" : `ossrh[_-]?pass(=| =|:| :)`,
		"ossrh_password" : `ossrh[_-]?password(=| =|:| :)`,
		"ossrh_secret" : `ossrh[_-]?secret(=| =|:| :)`,
		"ossrh_username" : `ossrh[_-]?username(=| =|:| :)`,
		"outlook_team" : `(https://outlook.office.com/webhook/[0-9a-f-]{36}@)`,
		"packagecloud_token" : `packagecloud[_-]?token(=| =|:| :)`,
		"pagerduty_apikey" : `pagerduty[_-]?apikey(=| =|:| :)`,
		"parse_js_key" : `parse[_-]?js[_-]?key(=| =|:| :)`,
		"password_in_url" : `[a-zA-Z]{3,10}://[^/\s:@]{3,20}:[^/\s:@]{3,20}@.{1,100}["'\s]`,
		"passwordtravis" : `passwordtravis(=| =|:| :)`,
		"paypal" : `[a-zA-Z0-9]{1,2}([E][A-Z]{1}[a-zA-Z0-9_-]{78})[a-zA-Z0-9]{1,2}$`,
		"paypal_braintree_access_token" : `access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}`,
		"paypal_client_secret" : `paypal[_-]?client[_-]?secret(=| =|:| :)`,
		"percy_project" : `percy[_-]?project(=| =|:| :)`,
		"percy_token" : `percy[_-]?token(=| =|:| :)`,
		"personal_key" : `personal[_-]?key(=| =|:| :)`,
		"personal_secret" : `personal[_-]?secret(=| =|:| :)`,
		"pg_database" : `pg[_-]?database(=| =|:| :)`,
		"pg_host" : `pg[_-]?host(=| =|:| :)`,
		"pgp" : `-----BEGIN PGP PRIVATE KEY BLOCK-----`,
		"pgp_private_key_block" : `-----BEGIN PGP PRIVATE KEY BLOCK-----`,
		"picatic_api_key_disclosure" : `sk_live_[0-9a-z]{32}`,
		"picatic_api_key" : `sk_live_[0-9a-z]{32}`,
		"pictatic_api_key" : `sk_live_[0-9a-z]{32}`,
		"places_api_key" : `places[_-]?api[_-]?key(=| =|:| :)`,
		"places_apikey" : `places[_-]?apikey(=| =|:| :)`,
		"plotly_apikey" : `plotly[_-]?apikey(=| =|:| :)`,
		"plugin_password" : `plugin[_-]?password(=| =|:| :)`,
		"postgres_env_postgres_db" : `postgres[_-]?env[_-]?postgres[_-]?db(=| =|:| :)`,
		"postgres_env_postgres_password" : `postgres[_-]?env[_-]?postgres[_-]?password(=| =|:| :)`,
		"postgresql_db" : `postgresql[_-]?db(=| =|:| :)`,
		"postgresql_pass" : `postgresql[_-]?pass(=| =|:| :)`,
		"prebuild_auth" : `prebuild[_-]?auth(=| =|:| :)`,
		"preferred_username" : `preferred[_-]?username(=| =|:| :)`,
		"pring_mail_username" : `pring[_-]?mail[_-]?username(=| =|:| :)`,
		"private_key" : `(?i)-----(?:(?:BEGIN|END) )(?:(?:EC|PGP|DSA|RSA|OPENSSH).)?PRIVATE.KEY(.BLOCK)?-----`,
		"private_signing_password" : `private[_-]?signing[_-]?password(=| =|:| :)`,
		"prod_access_key_id" : `prod[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"prod_password" : `prod[_-]?password(=| =|:| :)`,
		"prod_secret_key" : `prod[_-]?secret[_-]?key(=| =|:| :)`,
		"project_config" : `project[_-]?config(=| =|:| :)`,
		"publish_access" : `publish[_-]?access(=| =|:| :)`,
		"publish_key" : `publish[_-]?key(=| =|:| :)`,
		"publish_secret" : `publish[_-]?secret(=| =|:| :)`,
		"pushover_token" : `pushover[_-]?token(=| =|:| :)`,
		"pypi_passowrd" : `pypi[_-]?passowrd(=| =|:| :)`,
		"qiita_token" : `qiita[_-]?token(=| =|:| :)`,
		"quip_token" : `quip[_-]?token(=| =|:| :)`,
		"rabbitmq_password" : `rabbitmq[_-]?password(=| =|:| :)`,
		"randrmusicapiaccesstoken" : `randrmusicapiaccesstoken(=| =|:| :)`,
		"rediscloud_url" : `rediscloud[_-]?url(=| =|:| :)`,
		"redis_stunnel_urls" : `redis[_-]?stunnel[_-]?urls(=| =|:| :)`,
		"redis_url" : `(REDIS_URL).+`,
		"refresh_token" : `refresh[_-]?token(=| =|:| :)`,
		"registry_pass" : `registry[_-]?pass(=| =|:| :)`,
		"registry_secure" : `registry[_-]?secure(=| =|:| :)`,
		"release_gh_token" : `release[_-]?gh[_-]?token(=| =|:| :)`,
		"release_token" : `release[_-]?token(=| =|:| :)`,
		"reporting_webdav_pwd" : `reporting[_-]?webdav[_-]?pwd(=| =|:| :)`,
		"reporting_webdav_url" : `reporting[_-]?webdav[_-]?url(=| =|:| :)`,
		"repotoken" : `repotoken(=| =|:| :)`,
		"rest_api_key" : `rest[_-]?api[_-]?key(=| =|:| :)`,
		"rinkeby_private_key" : `rinkeby[_-]?private[_-]?key(=| =|:| :)`,
		"rkcs8" : `-----BEGIN PRIVATE KEY-----`,
		"ropsten_private_key" : `ropsten[_-]?private[_-]?key(=| =|:| :)`,
		"route53_access_key_id" : `route53[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"rsa" : `-----BEGIN RSA PRIVATE KEY-----`,
		"rsa_private_key" : `-----BEGIN RSA PRIVATE KEY-----`,
		"rtd_key_pass" : `rtd[_-]?key[_-]?pass(=| =|:| :)`,
		"rtd_store_pass" : `rtd[_-]?store[_-]?pass(=| =|:| :)`,
		"rubygems_auth_token" : `rubygems[_-]?auth[_-]?token(=| =|:| :)`,
		"s3_access_key_id" : `s3[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"s3_access_key" : `s3[_-]?access[_-]?key(=| =|:| :)`,
		"s3_bucket_name_app_logs" : `s3[_-]?bucket[_-]?name[_-]?app[_-]?logs(=| =|:| :)`,
		"s3_bucket_name_assets" : `s3[_-]?bucket[_-]?name[_-]?assets(=| =|:| :)`,
		"s3_external_3_amazonaws_com" : `s3[_-]?external[_-]?3[_-]?amazonaws[_-]?com(=| =|:| :)`,
		"s3_key_app_logs" : `s3[_-]?key[_-]?app[_-]?logs(=| =|:| :)`,
		"s3_key_assets" : `s3[_-]?key[_-]?assets(=| =|:| :)`,
		"s3_key" : `s3[_-]?key(=| =|:| :)`,
		"s3_secret_app_logs" : `s3[_-]?secret[_-]?app[_-]?logs(=| =|:| :)`,
		"s3_secret_assets" : `s3[_-]?secret[_-]?assets(=| =|:| :)`,
		"s3_secret_key" : `s3[_-]?secret[_-]?key(=| =|:| :)`,
		"s3_user_secret" : `s3[_-]?user[_-]?secret(=| =|:| :)`,
		"sacloud_access_token" : `sacloud[_-]?access[_-]?token(=| =|:| :)`,
		"sacloud_access_token_secret" : `sacloud[_-]?access[_-]?token[_-]?secret(=| =|:| :)`,
		"sacloud_api" : `sacloud[_-]?api(=| =|:| :)`,
		"salesforce_bulk_test_password" : `salesforce[_-]?bulk[_-]?test[_-]?password(=| =|:| :)`,
		"salesforce_bulk_test_security_token" : `salesforce[_-]?bulk[_-]?test[_-]?security[_-]?token(=| =|:| :)`,
		"sandbox_access_token" : `sandbox[_-]?access[_-]?token(=| =|:| :)`,
		"sandbox_aws_access_key_id" : `sandbox[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"sandbox_aws_secret_access_key" : `sandbox[_-]?aws[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"sauce_access_key" : `sauce[_-]?access[_-]?key(=| =|:| :)`,
		"sauce_token" : `(sauce.{0,50}("|')?[0-9a-f-]{36}("|')?)`,
		"scrutinizer_token" : `scrutinizer[_-]?token(=| =|:| :)`,
		"sdr_token" : `sdr[_-]?token(=| =|:| :)`,
		"secret_0" : `secret[_-]?0(=| =|:| :)`,
		"secret_10" : `secret[_-]?10(=| =|:| :)`,
		"secret_11" : `secret[_-]?11(=| =|:| :)`,
		"secret_1" : `secret[_-]?1(=| =|:| :)`,
		"secret_2" : `secret[_-]?2(=| =|:| :)`,
		"secret_3" : `secret[_-]?3(=| =|:| :)`,
		"secret_4" : `secret[_-]?4(=| =|:| :)`,
		"secret_5" : `secret[_-]?5(=| =|:| :)`,
		"secret_6" : `secret[_-]?6(=| =|:| :)`,
		"secret_7" : `secret[_-]?7(=| =|:| :)`,
		"secret_8" : `secret[_-]?8(=| =|:| :)`,
		"secret_9" : `secret[_-]?9(=| =|:| :)`,
		"secretaccesskey" : `secretaccesskey(=| =|:| :)`,
		"secret_key_base" : `secret[_-]?key[_-]?base(=| =|:| :)`,
		"secretkey" : `secretkey(=| =|:| :)`,
		"segment_api_key" : `segment[_-]?api[_-]?key(=| =|:| :)`,
		"selion_log_level_dev" : `selion[_-]?log[_-]?level[_-]?dev(=| =|:| :)`,
		"selion_selenium_host" : `selion[_-]?selenium[_-]?host(=| =|:| :)`,
		"sendgrid_api_key" : `(SG.[a-zA-Z0-9-]{16,32}.[a-zA-Z0-9-]{16,64})`,
		"sendgrid_key" : `sendgrid[_-]?key(=| =|:| :)`,
		"sendgrid_password" : `sendgrid[_-]?password(=| =|:| :)`,
		"sendgrid" : `sendgrid(=| =|:| :)`,
		"sendgrid_username" : `sendgrid[_-]?username(=| =|:| :)`,
		"sendgrid_user" : `sendgrid[_-]?user(=| =|:| :)`,
		"sendwithus_key" : `sendwithus[_-]?key(=| =|:| :)`,
		"sentry_auth_token" : `sentry[_-]?auth[_-]?token(=| =|:| :)`,
		"sentry_default_org" : `sentry[_-]?default[_-]?org(=| =|:| :)`,
		"sentry_endpoint" : `sentry[_-]?endpoint(=| =|:| :)`,
		"sentry_key" : `sentry[_-]?key(=| =|:| :)`,
		"service_account_secret" : `service[_-]?account[_-]?secret(=| =|:| :)`,
		"ses_access_key" : `ses[_-]?access[_-]?key(=| =|:| :)`,
		"ses_secret_key" : `ses[_-]?secret[_-]?key(=| =|:| :)`,
		"setdstaccesskey" : `setdstaccesskey(=| =|:| :)`,
		"setdstsecretkey" : `setdstsecretkey(=| =|:| :)`,
		"setsecretkey" : `setsecretkey(=| =|:| :)`,
		"shopify_access_token" : `shpat_[a-fA-F0-9]{32}`,
		"shopify_custom_app_access_token" : `shpca_[a-fA-F0-9]{32}`,
		"shopify_private_app_access_token" : `shppa_[a-fA-F0-9]{32}`,
		"shopify_shared_secret" : `shpss_[a-fA-F0-9]{32}`,
		"shoppable_service_auth" : `data-shoppable-auth-token.+`,
		"signing_key_password" : `signing[_-]?key[_-]?password(=| =|:| :)`,
		"signing_key_secret" : `signing[_-]?key[_-]?secret(=| =|:| :)`,
		"signing_key_sid" : `signing[_-]?key[_-]?sid(=| =|:| :)`,
		"signing_key" : `signing[_-]?key(=| =|:| :)`,
		"slack_access_token" : `xoxb-[0-9A-Za-z\-]{51}`,
		"slack_api_key" : `xox[baprs]-([0-9a-zA-Z]{10,48})?`,
		"slack_api_token" : `(xox[aboprs]-([0-9a-zA-Z-]{8,})?)`,
		"slack_token" : `(xox[pborsa]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})`,
		"slack_user_token_disclosure" : `xoxp-[0-9A-Za-z\-]{72}`,
		"slack_webhook" : `https://hooks\.slack\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}`,
		"slack_webhook_url" : `(hooks.slack.com/services/T[A-Z0-9]{8}/B[A-Z0-9]{8}/[a-zA-Z0-9]{1,})`,
		"slash_developer_space_key" : `slash[_-]?developer[_-]?space[_-]?key(=| =|:| :)`,
		"slash_developer_space" : `slash[_-]?developer[_-]?space(=| =|:| :)`,
		"slate_user_email" : `slate[_-]?user[_-]?email(=| =|:| :)`,
		"snoowrap_client_secret" : `snoowrap[_-]?client[_-]?secret(=| =|:| :)`,
		"snoowrap_password" : `snoowrap[_-]?password(=| =|:| :)`,
		"snoowrap_refresh_token" : `snoowrap[_-]?refresh[_-]?token(=| =|:| :)`,
		"snyk_api_token" : `snyk[_-]?api[_-]?token(=| =|:| :)`,
		"snyk_token" : `snyk[_-]?token(=| =|:| :)`,
		"socrata_app_token" : `socrata[_-]?app[_-]?token(=| =|:| :)`,
		"socrata_password" : `socrata[_-]?password(=| =|:| :)`,
		"sonar_organization_key" : `sonar[_-]?organization[_-]?key(=| =|:| :)`,
		"sonar_project_key" : `sonar[_-]?project[_-]?key(=| =|:| :)`,
		"sonarqube_docs_api_key" : `(sonar.{0,50}("|')?[0-9a-f]{40}("|')?)`,
		"sonar_token" : `sonar[_-]?token(=| =|:| :)`,
		"sonatype_gpg_key_name" : `sonatype[_-]?gpg[_-]?key[_-]?name(=| =|:| :)`,
		"sonatype_gpg_passphrase" : `sonatype[_-]?gpg[_-]?passphrase(=| =|:| :)`,
		"sonatype_nexus_password" : `sonatype[_-]?nexus[_-]?password(=| =|:| :)`,
		"sonatype_pass" : `sonatype[_-]?pass(=| =|:| :)`,
		"sonatype_password" : `sonatype[_-]?password(=| =|:| :)`,
		"sonatypepassword" : `sonatypepassword(=| =|:| :)`,
		"sonatype_token_password" : `sonatype[_-]?token[_-]?password(=| =|:| :)`,
		"sonatype_token_user" : `sonatype[_-]?token[_-]?user(=| =|:| :)`,
		"soundcloud_client_secret" : `soundcloud[_-]?client[_-]?secret(=| =|:| :)`,
		"soundcloud_password" : `soundcloud[_-]?password(=| =|:| :)`,
		"spaces_access_key_id" : `spaces[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"spaces_secret_access_key" : `spaces[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"spotify_api_access_token" : `spotify[_-]?api[_-]?access[_-]?token(=| =|:| :)`,
		"spotify_api_client_secret" : `spotify[_-]?api[_-]?client[_-]?secret(=| =|:| :)`,
		"spring_mail_password" : `spring[_-]?mail[_-]?password(=| =|:| :)`,
		"sqsaccesskey" : `sqsaccesskey(=| =|:| :)`,
		"sqssecretkey" : `sqssecretkey(=| =|:| :)`,
		"square_accesss_token" : `sq0atp-[0-9A-Za-z\-_]{22}`,
		"square_access_token" : `sq0atp-[0-9A-Za-z\-_]{22}`,
		"square_api_key" : `sq0(atp|csp)-[0-9a-z-_]{22,43}`,
		"square_app_secret" : `(sq0[a-z]{3}-[0-9A-Za-z-_]{20,50})`,
		"square_oauth_secret" : `sq0csp-[0-9A-Za-z\-_]{43}`,
		"square_reader_sdk_repository_password" : `square[_-]?reader[_-]?sdk[_-]?repository[_-]?password(=| =|:| :)`,
		"srcclr_api_token" : `srcclr[_-]?api[_-]?token(=| =|:| :)`,
		"ssh" : `-----BEGIN OPENSSH PRIVATE KEY-----`,
		"ssh_(dsa)_private_key" : `-----BEGIN DSA PRIVATE KEY-----`,
		"ssh_(ec)_private_key" : `-----BEGIN EC PRIVATE KEY-----`,
		"sshpass" : `sshpass(=| =|:| :)`,
		"ssh_password" : `(sshpass -p.*['|"])`,
		"ssmtp_config" : `ssmtp[_-]?config(=| =|:| :)`,
		"staging_base_url_runscope" : `staging[_-]?base[_-]?url[_-]?runscope(=| =|:| :)`,
		"starship_account_sid" : `starship[_-]?account[_-]?sid(=| =|:| :)`,
		"starship_auth_token" : `starship[_-]?auth[_-]?token(=| =|:| :)`,
		"star_test_aws_access_key_id" : `star[_-]?test[_-]?aws[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"star_test_bucket" : `star[_-]?test[_-]?bucket(=| =|:| :)`,
		"star_test_location" : `star[_-]?test[_-]?location(=| =|:| :)`,
		"star_test_secret_access_key" : `star[_-]?test[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"stormpath_api_key_id" : `stormpath[_-]?api[_-]?key[_-]?id(=| =|:| :)`,
		"stormpath_api_key_secret" : `stormpath[_-]?api[_-]?key[_-]?secret(=| =|:| :)`,
		"stripe_api_key" : `sk_live_[0-9a-zA-Z]{24}`,
		"stripe_private" : `stripe[_-]?private(=| =|:| :)`,
		"stripe_public_live_key" : `pk_live_[0-9a-z]{24}`,
		"stripe_public" : `stripe[_-]?public(=| =|:| :)`,
		"stripe_public_test_key" : `pk_test_[0-9a-z]{24}`,
		"stripe_restriced_key" : `rk_(?:live|test)_[0-9a-zA-Z]{24}`,
		"stripe_restricted_api_key" : `rk_live_[0-9a-zA-Z]{24}`,
		"stripe_restricted_api" : `(rk_live_[0-9a-zA-Z]{24,34})`,
		"stripe_secret_key" : `sk_(?:live|test)_[0-9a-zA-Z]{24}`,
		"stripe_secret_live_key" : `(sk|rk)_live_[0-9a-z]{24}`,
		"stripe_secret_test_key" : `(sk|rk)_test_[0-9a-z]{24}`,
		"stripe_standard_api" : `(sk_live_[0-9a-zA-Z]{24,34})`,
		"strip_publishable_key" : `strip[_-]?publishable[_-]?key(=| =|:| :)`,
		"strip_secret_key" : `strip[_-]?secret[_-]?key(=| =|:| :)`,
		"surge_login" : `surge[_-]?login(=| =|:| :)`,
		"surge_token" : `surge[_-]?token(=| =|:| :)`,
		"svn_pass" : `svn[_-]?pass(=| =|:| :)`,
		"telegram_bot_api_key" : `[0-9]+:AA[0-9A-Za-z\-_]{33}`,
		"telegram_secret" : `d{5,}:A[0-9a-z_-]{34,34}`,
		"tesco_api_key" : `tesco[_-]?api[_-]?key(=| =|:| :)`,
		"tester_keys_password" : `tester[_-]?keys[_-]?password(=| =|:| :)`,
		"test_github_token" : `test[_-]?github[_-]?token(=| =|:| :)`,
		"thera_oss_access_key" : `thera[_-]?oss[_-]?access[_-]?key(=| =|:| :)`,
		"token_core_java" : `token[_-]?core[_-]?java(=| =|:| :)`,
		"travis_access_token" : `travis[_-]?access[_-]?token(=| =|:| :)`,
		"travis_api_token" : `travis[_-]?api[_-]?token(=| =|:| :)`,
		"travis_branch" : `travis[_-]?branch(=| =|:| :)`,
		"travis_com_token" : `travis[_-]?com[_-]?token(=| =|:| :)`,
		"travis_e2e_token" : `travis[_-]?e2e[_-]?token(=| =|:| :)`,
		"travis_gh_token" : `travis[_-]?gh[_-]?token(=| =|:| :)`,
		"travis_pull_request" : `travis[_-]?pull[_-]?request(=| =|:| :)`,
		"travis_secure_env_vars" : `travis[_-]?secure[_-]?env[_-]?vars(=| =|:| :)`,
		"travis_token" : `travis[_-]?token(=| =|:| :)`,
		"trello_url" : `https://trello.com/b/[0-9a-z]/[0-9a-z_-]+`,
		"trex_client_token" : `trex[_-]?client[_-]?token(=| =|:| :)`,
		"trex_okta_client_token" : `trex[_-]?okta[_-]?client[_-]?token(=| =|:| :)`,
		"twilio_api_key" : `SK[0-9a-fA-F]{32}`,
		"twilio_api_secret" : `twilio[_-]?api[_-]?secret(=| =|:| :)`,
		"twilio_chat_account_api_service" : `twilio[_-]?chat[_-]?account[_-]?api[_-]?service(=| =|:| :)`,
		"twilio_configuration_sid" : `twilio[_-]?configuration[_-]?sid(=| =|:| :)`,
		"twilio_sid" : `twilio[_-]?sid(=| =|:| :)`,
		"twilio_token" : `twilio[_-]?token(=| =|:| :)`,
		"twine_password" : `twine[_-]?password(=| =|:| :)`,
		"twitter_access_token" : `[tT][wW][iI][tT][tT][eE][rR].*[1-9][0-9]+-[0-9a-zA-Z]{40}`,
		"twitter" : `([a-zA-Z0-9]{1,2}([a-zA-Z0-9]{50})[a-zA-Z0-9]{1,2}$)`,
		"twitter_client_id" : `(twitter(.{0,20})?['"][0-9a-z]{18,25}['"])`,
		"twitter_consumer_key" : `twitter[_-]?consumer[_-]?key(=| =|:| :)`,
		"twitter_consumer_secret" : `twitter[_-]?consumer[_-]?secret(=| =|:| :)`,
		"twitteroauthaccesssecret" : `twitteroauthaccesssecret(=| =|:| :)`,
		"twitteroauthaccesstoken" : `twitteroauthaccesstoken(=| =|:| :)`,
		"twitter_oauth" : `[tT][wW][iI][tT][tT][eE][rR].*['|"][0-9a-zA-Z]{35,44}['|"]`,
		"twitter_secret" : `(?i)twitter(.{0,20})?[0-9a-z]{35,44}`,
		"twitter_secret_key" : `twitter(.{0,20})?['"][0-9a-z]{35,44}['"]`,
		"unity_password" : `unity[_-]?password(=| =|:| :)`,
		"unity_serial" : `unity[_-]?serial(=| =|:| :)`,
		"urban_key" : `urban[_-]?key(=| =|:| :)`,
		"urban_master_secret" : `urban[_-]?master[_-]?secret(=| =|:| :)`,
		"urban_secret" : `urban[_-]?secret(=| =|:| :)`,
		"us_east_1_elb_amazonaws_com" : `us[_-]?east[_-]?1[_-]?elb[_-]?amazonaws[_-]?com(=| =|:| :)`,
		"user_assets_access_key_id" : `user[_-]?assets[_-]?access[_-]?key[_-]?id(=| =|:| :)`,
		"user_assets_secret_access_key" : `user[_-]?assets[_-]?secret[_-]?access[_-]?key(=| =|:| :)`,
		"usertravis" : `usertravis(=| =|:| :)`,
		"use_ssh" : `use[_-]?ssh(=| =|:| :)`,
		"vault_token" : `([sb]\.[a-zA-Z0-9]{24})`,
		"vip_github_build_repo_deploy_key" : `vip[_-]?github[_-]?build[_-]?repo[_-]?deploy[_-]?key(=| =|:| :)`,
		"vip_github_deploy_key_pass" : `vip[_-]?github[_-]?deploy[_-]?key[_-]?pass(=| =|:| :)`,
		"vip_github_deploy_key" : `vip[_-]?github[_-]?deploy[_-]?key(=| =|:| :)`,
		"virustotal_apikey" : `virustotal[_-]?apikey(=| =|:| :)`,
		"visual_recognition_api_key" : `visual[_-]?recognition[_-]?api[_-]?key(=| =|:| :)`,
		"vscetoken" : `vscetoken(=| =|:| :)`,
		"v_sfdc_client_secret" : `v[_-]?sfdc[_-]?client[_-]?secret(=| =|:| :)`,
		"v_sfdc_password" : `v[_-]?sfdc[_-]?password(=| =|:| :)`,
		"wakatime_api_key" : `wakatime[_-]?api[_-]?key(=| =|:| :)`,
		"watson_conversation_password" : `watson[_-]?conversation[_-]?password(=| =|:| :)`,
		"watson_device_password" : `watson[_-]?device[_-]?password(=| =|:| :)`,
		"watson_password" : `watson[_-]?password(=| =|:| :)`,
		"widget_basic_password_2" : `widget[_-]?basic[_-]?password[_-]?2(=| =|:| :)`,
		"widget_basic_password_3" : `widget[_-]?basic[_-]?password[_-]?3(=| =|:| :)`,
		"widget_basic_password_4" : `widget[_-]?basic[_-]?password[_-]?4(=| =|:| :)`,
		"widget_basic_password_5" : `widget[_-]?basic[_-]?password[_-]?5(=| =|:| :)`,
		"widget_basic_password" : `widget[_-]?basic[_-]?password(=| =|:| :)`,
		"widget_fb_password_2" : `widget[_-]?fb[_-]?password[_-]?2(=| =|:| :)`,
		"widget_fb_password_3" : `widget[_-]?fb[_-]?password[_-]?3(=| =|:| :)`,
		"widget_fb_password" : `widget[_-]?fb[_-]?password(=| =|:| :)`,
		"widget_test_server" : `widget[_-]?test[_-]?server(=| =|:| :)`,
		"wincert_password" : `wincert[_-]?password(=| =|:| :)`,
		"wordpress_db_password" : `wordpress[_-]?db[_-]?password(=| =|:| :)`,
		"wordpress_db_user" : `wordpress[_-]?db[_-]?user(=| =|:| :)`,
		"wpjm_phpunit_google_geocode_api_key" : `wpjm[_-]?phpunit[_-]?google[_-]?geocode[_-]?api[_-]?key(=| =|:| :)`,
		"wporg_password" : `wporg[_-]?password(=| =|:| :)`,
		"wpt_db_password" : `wpt[_-]?db[_-]?password(=| =|:| :)`,
		"wpt_db_user" : `wpt[_-]?db[_-]?user(=| =|:| :)`,
		"wpt_prepare_dir" : `wpt[_-]?prepare[_-]?dir(=| =|:| :)`,
		"wpt_report_api_key" : `wpt[_-]?report[_-]?api[_-]?key(=| =|:| :)`,
		"wpt_ssh_connect" : `wpt[_-]?ssh[_-]?connect(=| =|:| :)`,
		"wpt_ssh_private_key_base64" : `wpt[_-]?ssh[_-]?private[_-]?key[_-]?base64(=| =|:| :)`,
		"www_googleapis_com" : `www[_-]?googleapis[_-]?com(=| =|:| :)`,
		"yangshun_gh_password" : `yangshun[_-]?gh[_-]?password(=| =|:| :)`,
		"yangshun_gh_token" : `yangshun[_-]?gh[_-]?token(=| =|:| :)`,
		"yt_account_client_secret" : `yt[_-]?account[_-]?client[_-]?secret(=| =|:| :)`,
		"yt_account_refresh_token" : `yt[_-]?account[_-]?refresh[_-]?token(=| =|:| :)`,
		"yt_api_key" : `yt[_-]?api[_-]?key(=| =|:| :)`,
		"yt_client_secret" : `yt[_-]?client[_-]?secret(=| =|:| :)`,
		"yt_partner_client_secret" : `yt[_-]?partner[_-]?client[_-]?secret(=| =|:| :)`,
		"yt_partner_refresh_token" : `yt[_-]?partner[_-]?refresh[_-]?token(=| =|:| :)`,
		"yt_server_api_key" : `yt[_-]?server[_-]?api[_-]?key(=| =|:| :)`,
		"zapier_webhook" : `https://(?:www.)?hooks\.zapier\.com/hooks/catch/[A-Za-z0-9]+/[A-Za-z0-9]+/`,
		"zendesk_travis_github" : `zendesk[_-]?travis[_-]?github(=| =|:| :)`,
		"zensonatypepassword" : `zensonatypepassword(=| =|:| :)`,
		"zhuliang_gh_token" : `zhuliang[_-]?gh[_-]?token(=| =|:| :)`,
		"zoho_webhook" : `https://creator\.zoho\.com/api/[A-Za-z0-9/\-_\.]+\?authtoken=[A-Za-z0-9]+`,
		"zopim_account_key" : `zopim[_-]?account[_-]?key(=| =|:| :)`,
	}

	for key, element := range regex_map {
		r := regexp.MustCompile(element)
		matches := r.FindAllString(content, -1)
		for _, v := range matches {
			fmt.Println("[+] Found " + "[" + key + "]" + "	[" + v + "]" + "	[" + Burl + "]")
		}
	}


}

func linkFinder(content, baseURL string, completeURL, statusCode bool) {
    linkRegex := `(?:"|')(((?:[a-zA-Z]{1,10}://|//)[^"'/]{1,}\.[a-zA-Z]{2,}[^"']{0,})|((?:/|\.\./|\./)[^"'><,;| *()(%%$^/\\\[\]][^"'><,;|()]{1,})|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{1,}\.(?:[a-zA-Z]{1,4}|action)(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-/]{1,}/[a-zA-Z0-9_\-/]{3,}(?:[\?|#][^"|']{0,}|))|([a-zA-Z0-9_\-]{1,}\.(?:php|asp|aspx|jsp|json|action|html|js|txt|xml)(?:[\?|#][^"|']{0,}|)))(?:"|')`

    r := regexp.MustCompile(linkRegex)
    matches := r.FindAllString(content, -1)

    base, err := url.Parse(baseURL)
    if err != nil {
        fmt.Println("")
    }

    for _, v := range matches {
        cleanedMatch := strings.Trim(v, `"'`)
        link, err := url.Parse(cleanedMatch)
        if err != nil {
            continue
        }
        if completeURL {
            link = base.ResolveReference(link)
        }
        if statusCode {
            request(link.String(), true)
        } else {
            fmt.Printf("[+] Found link: [%s] in [%s] \n", link.String(),  base.String())
        }
    }
}


func main() {
	var concurrency int
	var enableLinkFinder, completeURL, checkStatus, enableSecretFinder bool
	flag.BoolVar(&enableLinkFinder, "l", false, "Enable linkFinder")
	flag.BoolVar(&completeURL, "e", false, "Complete Scope Url or not")
	flag.BoolVar(&checkStatus, "k", false, "Check status or not")
	flag.BoolVar(&enableSecretFinder, "s", false, "Enable secretFinder")
	flag.IntVar(&concurrency, "c", 10, "Number of concurrent workers")
	flag.Parse()
	urls := make(chan string, 10)
	go func() {
		sc := bufio.NewScanner(os.Stdin)
		for sc.Scan() {
			urls <- sc.Text()
		}
		close(urls)
		if err := sc.Err(); err != nil {
			fmt.Fprintf(os.Stderr, "failed to read input: %s\n", err)
		}
	}()

	wg := sync.WaitGroup{}
	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func() {
			for vUrl := range urls {
				res := request(vUrl, false)
				
				if enableSecretFinder {
					regexGrep(res, vUrl)
				}
				if enableLinkFinder {
					linkFinder(res, vUrl, false, false)
				}
				if completeURL {
					linkFinder(res, vUrl, true, false)
				}
				if checkStatus {
					linkFinder(res, vUrl, true, true)
				}
			}
			wg.Done()
		}()
	}
	wg.Wait()
}
